ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: fbdb971663560152
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 561, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 2c8a1519e705aec2
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 568, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 847c2275f56dcc40
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5900,password=847c2275f56dcc40']
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 1eb9f9962b4a3564
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5900,password=1eb9f9962b4a3564']
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
ERROR:root:LDAP Error: apsegundo invalid credentials
Traceback (most recent call last):
  File "./osdvt-server.py", line 178, in Auth
    l.simple_bind_s(dn,password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 207, in simple_bind_s
    return self.result(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 422, in result
    res_type,res_data,res_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 426, in result2
    res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 432, in result3
    ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 96, in _ldap_call
    result = func(*args,**kwargs)
INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
ERROR:root:LDAP Error: apsegundo invalid credentials
Traceback (most recent call last):
  File "./osdvt-server.py", line 178, in Auth
    l.simple_bind_s(dn,password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 207, in simple_bind_s
    return self.result(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 422, in result
    res_type,res_data,res_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 426, in result2
    res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 432, in result3
    ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 96, in _ldap_call
    result = func(*args,**kwargs)
INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: ec281757eaa6ee9b
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5900,password=ec281757eaa6ee9b']
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 11303027120b9a49
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5900,password=11303027120b9a49']
DEBUG:root:Free port found: 5901
DEBUG:root:Randon VideoToken OK.: 832153520486af41
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5901,password=832153520486af41']
DEBUG:root:Free port found: 5901
DEBUG:root:Randon VideoToken OK.: d7d7b4861838194c
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5901,password=d7d7b4861838194c']
DEBUG:root:Free port found: 5901
DEBUG:root:Randon VideoToken OK.: 3573224be6643848
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5901,password=3573224be6643848']
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
ERROR:root:LDAP Error: ldap://ldap.ucs.br
Traceback (most recent call last):
  File "./osdvt-server.py", line 169, in Auth
    dn = l.search_s(baseDN, searchScope, searchFilter, retrieveAttributes)[0][0]
IndexError: list index out of range
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
ERROR:root:LDAP Error: apsegundo invalid credentials
Traceback (most recent call last):
  File "./osdvt-server.py", line 178, in Auth
    l.simple_bind_s(dn,password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 207, in simple_bind_s
    return self.result(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 422, in result
    res_type,res_data,res_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 426, in result2
    res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 432, in result3
    ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 96, in _ldap_call
    result = func(*args,**kwargs)
INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
ERROR:root:LDAP Error: apsegundo invalid credentials
Traceback (most recent call last):
  File "./osdvt-server.py", line 178, in Auth
    l.simple_bind_s(dn,password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 207, in simple_bind_s
    return self.result(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 422, in result
    res_type,res_data,res_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 426, in result2
    res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 432, in result3
    ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 96, in _ldap_call
    result = func(*args,**kwargs)
INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
ERROR:root:LDAP Error: apsegundo invalid credentials
Traceback (most recent call last):
  File "./osdvt-server.py", line 178, in Auth
    l.simple_bind_s(dn,password)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 207, in simple_bind_s
    return self.result(msgid,all=1,timeout=self.timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 422, in result
    res_type,res_data,res_msgid = self.result2(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 426, in result2
    res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 432, in result3
    ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)
  File "/usr/lib64/python2.7/site-packages/ldap/ldapobject.py", line 96, in _ldap_call
    result = func(*args,**kwargs)
INVALID_CREDENTIALS: {'desc': 'Invalid credentials'}
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 7db6aa41a09d0f58
DEBUG:root:qemuargs: ['-M', 'pc', '-device', 'virtio-balloon-pci,id=balloon0,bus=pci.0', '-name', 'teste1', '-smp', '2,sockets=2,cores=1,threads=1', '-m', '100', '-net', 'nic,macaddr=12:34:56:00:00:21,model=rtl8139', '-net', 'tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh', '-soundhw', 'ac97', '-monitor', 'stdio', '-localtime', '-daemonize', '-pidfile', '/usr/local/osdvt/server/socket/teste1.pid', '-drive', 'file=/var/vms/win_xp_01.img', '-vga', 'qxl', '-spice', 'port=5900,password=7db6aa41a09d0f58']
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 89029658d89ddfe
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: e90fc91f53486f7
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: cefcf7f73182396a
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: baf254d8f3e16345
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 9ceba67c050ed5d
DEBUG:root:COMMAND: -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 100 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=9ceba67c050ed5d  
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: c7d57522f7890fd2
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 100 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=c7d57522f7890fd2
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 8bf739e0033c1012
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 100 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=8bf739e0033c1012
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: a7c1a3f3b34cda
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 100 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=a7c1a3f3b34cda
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: c127b5dabf1d83cd
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 100 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=c127b5dabf1d83cd
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server.py", line 571, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 735c30dfcba18621
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 100 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=735c30dfcba18621
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 4a81f46aedf69ffe
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 6b63ce12a6d89099
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 100 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=6b63ce12a6d89099
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: c2118f3b5aeb0d0a
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -snapshot -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=c2118f3b5aeb0d0a -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: fb0fbb8b8266442
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=fb0fbb8b8266442 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: bc4ca883ba8ea612
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=bc4ca883ba8ea612 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 9a28df04e8133cee
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=9a28df04e8133cee -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT: using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 581, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5901
DEBUG:root:Randon VideoToken OK.: 22372b4dd3a00677
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5901,password=22372b4dd3a00677 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: abe5c24c291f76b5
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=abe5c24c291f76b5 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5901
DEBUG:root:Randon VideoToken OK.: 8d801040a7de7b2
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5901,password=8d801040a7de7b2 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: f980b51bc226b8ac
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=f980b51bc226b8ac -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 584, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 4a0c9c2b9bdd4e8f
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=4a0c9c2b9bdd4e8f -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 4ceda90848e8742
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=4ceda90848e8742 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: b9bf0a9096e90773
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=b9bf0a9096e90773 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 624810ae71f113fe
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=624810ae71f113fe -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3  >> /usr/local/osdvt/server/log/osdvt-server.log 2>>&1
Adding tap1 to br0...
Bringing up tap1 for bridged mode...
do_spice_init: starting 0.9.1
spice_server_add_interface: SPICE_INTERFACE_KEYBOARD
spice_server_add_interface: SPICE_INTERFACE_MOUSE
spice_server_add_interface: SPICE_INTERFACE_QXL
red_worker_main: begin
ensure_display_channel_created: create display channel
ensure_cursor_channel_created: create cursor channel
spice_server_add_interface: SPICE_INTERFACE_RECORD
spice_server_add_interface: SPICE_INTERFACE_PLAYBACK
*** EHCI support is under development ***
spice_server_char_device_add_interface: CHAR_DEVICE usbredir
spice_server_char_device_add_interface: CHAR_DEVICE usbredir
spice_server_char_device_add_interface: CHAR_DEVICE usbredir
handle_dev_input: start
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 59f69fbef255cfde
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=59f69fbef255cfde -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File ".//osdvt-server", line 585, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 7e54ca0768b2651d
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=7e54ca0768b2651d -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3  >> /usr/local/osdvt/server/log/osdvt-server.log 2>> /usr/local/osdvt/server/log/osdvt-server.log
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: b9dc680b4f6730ff
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=b9dc680b4f6730ff -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5901
DEBUG:root:Randon VideoToken OK.: d76503a0d15161d
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5901,password=d76503a0d15161d -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3 -D /usr/local/osdvt/server/log/osdvt-server.log
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: d7f65525d1c524c5
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.imga -vga qxl -spice port=5900,password=d7f65525d1c524c5 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3 -D /usr/local/osdvt/server/log/osdvt-server.log
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 7ea0b1b57a893055
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.imga -vga qxl -spice port=5900,password=7ea0b1b57a893055 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3 -D /usr/local/osdvt/server/log/osdvt-server.log
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "/usr/local/osdvt/server/bin/osdvt-server", line 583, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 94079dc604983c79
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.imga -vga qxl -spice port=5900,password=94079dc604983c79 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 40379a3ba8cfd7be
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.imga -vga qxl -spice port=5900,password=40379a3ba8cfd7be -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: af82156b3b9ba7f
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.imga -vga qxl -spice port=5900,password=af82156b3b9ba7f -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: ca2a3f7e1ca2d16e
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=ca2a3f7e1ca2d16e -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: dbe984dd6b17e767
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:42:40:53,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=dbe984dd6b17e767 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 6854de3965ffd560
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:13:38:6f:cb,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=6854de3965ffd560 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 591, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: efd331ffe88c2f3c
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:78:7a:b9,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=efd331ffe88c2f3c -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Authenticating user. LDAP: ldap://ldap.ucs.br
DEBUG:root:Authenticating user. USER: apsegundo
DEBUG:root:Authenticating user. baseDN: ou=people,dc=ucs,dc=br
DEBUG:root:User apsegundo authenticated.
DEBUG:root:Free port found: 5901
DEBUG:root:Randon VideoToken OK.: 2fc334cf72cb99f5
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:6c:1d:26,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5901,password=2fc334cf72cb99f5 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: f92b26475aee1f78
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:76:14:5a,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=f92b26475aee1f78 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: b0e7d89a59eac760
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:7c:79:25,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=b0e7d89a59eac760 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 5c83d4cf5ece4391
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:5b:88:7f,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=5c83d4cf5ece4391 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: f43c2674f043037c
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:56:ab:87,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=f43c2674f043037c -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: a219acf01957576
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:7b:18:d5,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=a219acf01957576 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 613, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 61070386870fd62d
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:28:e0:7f,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=61070386870fd62d -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: c5816d99ff844981
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:61:cc:98,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=c5816d99ff844981 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 7744f2c2c185fc67
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:46:0c:7f,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=7744f2c2c185fc67 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 1b0281f8e5f50c79
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:46:0c:7f,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=1b0281f8e5f50c79 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 4372a831f4d95eba
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=4372a831f4d95eba -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 614, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 9e6050b5ae42778b
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=9e6050b5ae42778b -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 5a29296e5ca8ad13
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=5a29296e5ca8ad13 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:OSDVT 0.3 is running. Using /usr/bin/qemu-kvm.
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
ERROR:root:Connection lost trying to get STATUS.
Traceback (most recent call last):
  File "./osdvt-server", line 615, in <module>
    result = minhas_vms.AuthToken(dbhost, dbname, dbuser, dbpass, user, token)
NameError: name 'user' is not defined
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: fb5762fe8a136d15
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:23:9b:b6,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=fb5762fe8a136d15 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 26da68bd61c123f4
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:23:9b:b6,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=26da68bd61c123f4 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 26e088f796315851
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:23:9b:b6,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=26e088f796315851 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 1ba68c5f656ffa40
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:2d:e1:34,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=1ba68c5f656ffa40 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: cdbcb4a960f2de1f
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=12:34:56:00:00:21,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=cdbcb4a960f2de1f -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
DEBUG:root:Free port found: 5900
DEBUG:root:Randon VideoToken OK.: 4b47bbe1596f24c2
DEBUG:root:QEMU COMMAND: /usr/bin/qemu-kvm -D /usr/local/osdvt/server/log/osdvt-server.log -M pc -device virtio-balloon-pci,id=balloon0,bus=pci.0 -name teste1 -smp 2,sockets=2,cores=1,threads=1 -m 500 -net nic,macaddr=0C:81:12:30:18:ba,model=rtl8139 -net tap,ifname=tap1,script=/usr/local/osdvt/server/scripts/qemu-ifup.sh,downscript=/usr/local/osdvt/server/scripts/qemu-ifdown.sh -soundhw ac97 -monitor stdio -localtime -daemonize -pidfile /usr/local/osdvt/server/socket/teste1.pid -drive file=/var/vms/win_xp_01.img -vga qxl -spice port=5900,password=4b47bbe1596f24c2 -device virtio-serial -chardev spicevmc,id=vdagent,name=vdagent -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -readconfig /usr/local/osdvt/server/config/ich9-ehci-uhci.cfg -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,debug=3 -chardev spicevmc,name=usbredir,id=usbredirchardev3 -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3,debug=3
